---
title: "two-variables"
author: "SasanGN"
date: "December 13, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---


## import libraries
```{r}
library(ggplot2)
library(dplyr)
```

## Reading in the tab separated file // read.csv or read.delim
```{r}
getwd()
setwd("D://Documents//GitHub//100-days-of-code-challenge/")
list.files()
inFile <- read.csv('pseudo_facebook.tsv', sep= '\t')
## inFile2 <- read.delim('pseudo_facebook.tsv')
names(inFile)
```

## qplot vs ggplot syntax
```{r}
qplot(data = inFile, x= age, y= friend_count)

ggplot(aes(age, friend_count), data=inFile) + geom_point() +
  xlim(13,90)
summary(inFile$age)
```

## coord_trans
```{r}
ggplot(aes(age, friend_count), data = inFile) +
  geom_point(alpha = 1/20, position = position_jitter(h=0)) +
  xlim (13, 90) +
  coord_trans(y= 'sqrt')
```

## the relationship between friends initiated (y) vs age (x)
```{r}
ggplot(aes(age, friendships_initiated), data = inFile) + 
  geom_point(alpha = 0.1, position = position_jitter(h=0)) +
  coord_trans(y= 'sqrt')

```

## conditional means, group data by age
```{r}
age_groups <- group_by(inFile, age)
inFile.fc_by_age <- summarise(age_groups,
          friend_count_mean = mean(friend_count),
          friend_count_median = median(friend_count),
          n = n())
inFile.fc_by_age 

head(inFile.fc_by_age)
```

## alt. way to do the same result
```{r}
inFile.fc_by_age <- inFile %>%
  group_by(age) %>%
  summarise(friend_count_mean = mean(friend_count),
            friend_count_median = median(friend_count),
            n = n()) %>%
  arrange(age)
head(inFile.fc_by_age, 20)
```

## plot average friend count vs age using a line graph
## using geom_line()

```{r}
ggplot(aes(age, friend_count_mean), data = inFile.fc_by_age) + 
  geom_line()
```

## overlaying summaries with raw data!
```{r}
ggplot(aes(x= age, y = friend_count), data = inFile) +
  xlim (13,90) +
  geom_point(alpha = 0.05, position = position_jitter(h=0), color = 'red') +
  coord_trans(y='sqrt') +
  geom_line(stat = 'summary', fun.y = mean) +
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .5, linetype = 2, color = 'green')) + 
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .9, linetype = 2, color = 'blue'))

```

